- name: GitHub Action Deploy to WP Engine

      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
      # Deploy vars
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
        STG_ENV: "brewseeker2"
        REMOTE_PATH: "wp-content/themes/genesis-child-theme/"
